workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      groups:
        - ios_signing
    scripts:
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Build IPA
        script: |
          flutter build ipa --release --no-codesign
      - name: Debug IPA output
        script: |
          echo "📦 Check build/ios/ipa directory:"
          ls -al build/ios/ipa
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/ipa/*.dSYM.zip
