- name: Build IPA
  script: |
    flutter build ios --release --no-codesign

    xcodebuild \
      -workspace ios/Runner.xcworkspace \
      -scheme Runner \
      -configuration Release \
      -sdk iphoneos \
      -archivePath build/ios/archive/MyApp.xcarchive \
      archive

    xcodebuild -exportArchive \
      -archivePath build/ios/archive/MyApp.xcarchive \
      -exportOptionsPlist ios/ExportOptions.plist \
      -exportPath build/ios/ipa
