workflows:
  build_ios:
    name: Build iOS App with Code Signing and IPA Export
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    certificates:
      - certificate_url: ENCRYPTED
        certificate_password: ENCRYPTED
    provisioning_profiles:
      - ENCRYPTED

    scripts:
      - name: Install dependencies
        script: |
          flutter pub get

      - name: Build Xcode archive
        script: |
          flutter build ios --release --no-codesign
          xcodebuild -workspace ios/Runner.xcworkspace \
                     -scheme Runner \
                     -configuration Release \
                     -archivePath build/ios/archive/Runner.xcarchive \
                     archive

      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
                     -archivePath build/ios/archive/Runner.xcarchive \
                     -exportOptionsPlist ios/exportOptions.plist \
                     -exportPath build/ios/ipa

    artifacts:
      - build/ios/ipa/*.ipa
