workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      groups:
        - ios_signing
    scripts:
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Build IPA
        script: |
          flutter build ipa --release --no-codesign
    artifacts:
      paths:
        - build/ios/ipa/*.ipa
        - build/ios/ipa/*.dSYM.zip