name: infmaxai_flutter_app
description: A modified Flutter app for PDF annotation and drawing.
publish_to: 'none'

environment:
  sdk: '^3.4.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
